### ISSUE TITLE
Error with scaffold

### ISSUE THREAD

**Issue by xavdid** [zapier/zapier-platform-cli#14]
Version:

```
zapier-platform-cli/0.9.9
node/v4.3.2
```

I was trying to add a trigger to my app and got the following. `search` and `action` work fine

```
zapier scaffold trigger "Game" --debug
Adding trigger scaffold to your project.


ReferenceError: INPUT_FIELDS is not defined
    at eval (lodash.templateSources[5]:23:11)
    at /Users/david/projects/zapier-platform-cli/lib/commands/scaffold.js:53:69
    at run (/Users/david/projects/zapier-platform-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/david/projects/zapier-platform-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/david/projects/zapier-platform-cli/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickDomainCallback (node.js:385:13)

Error!
```

**Comment by bryanhelmig** [comment]
I think we just need to pass `INPUT_FIELDS: ''` into the scaffold templates - I believe @stevemolitor added support for `inputFields` during the `zapier convert` work and just missed this edge. I don't think `_.template` has support for missing variables.
