### ISSUE TITLE
zapier validate - Validation mismatch and too generic error message

### ISSUE THREAD

**Issue by marcinzaremba** [zapier/zapier-platform-cli#314]
## What would you like to change?

While running `zapier validate` code is validated locally against schema with success but unfortunately it sometimes appears invalid on server-side (different validation method, some unsupported structures, some specific edge cases, schema version mismatch?) when supposedly running style check against Zapier API. The effect is user does not know what are the alleged issues with the style nor with structure because locally everything is fine and server side does not provide any meaningful explanation.

Regular output:
```
$ zapier validate
Validating project locally.
No structural errors found during validation routine.
This project is structurally sound!

Checking app style.

Error! "https://zapier.com/api/platform/cli/style-check" returned "403" saying "App must validate against schema before checking style"
```

Output with debug (still not very helpful):
```
$ zapier validate --debug

Validating project locally.
No structural errors found during validation routine.
This project is structurally sound!

Checking app style.
>> POST https://zapier.com/api/platform/cli/style-check
>> {"version":"1.0.0","platformVersion":"6.0.0","beforeRequest":[null],"afterResponse":[],"triggers":{"paymentCreated":{"key":"paymentCreated","noun":"Payment","display":{"label":"New Payment","description":"****"},"operation":{"type":"hook","performSubscribe":"$func$2$f$","performUnsubscribe":"$func$2$f$","perform":"$func$2$f$","performList":"$func$2$f$","outputFields":[{"key":"id","label":"ID"}]}},"paymentStatusUpdated":{"key":"paymentStatusUpdated","noun":"Payment","display":{"label":"Payment Status Changed","description":"****"},"operation":{"perform":"$func$0$f$"}}},"searches":{},"creates":{},"searchOrCreates":{},"zip_file":"raw zip removed in logs"}
<< 403
<< {"errors": ["App must validate against schema before checking style"]}


Error: "https://zapier.com/api/platform/cli/style-check" returned "403" saying "App must validate against schema before checking style"
    at /usr/lib/node_modules/zapier-platform-cli/lib/utils/api.js:119:15
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Error!
```

Possible solutions:
- How about providing detailed explanation what is wrong with schema when validating on server-side (like on client-side) if a schema check is run either way on server side before style check?
- How about validating once on server-side not to provide two different answers to the same question: is application correct from schema standpoint?
(single point of truth)

## Your Environment

* CLI Version (`zapier -v`):
zapier-platform-cli/6.0.0
zapier-platform-core/6.0.0
node/v8.11.1
* Operating System and version:
Ubuntu Linux 16.04 LTS

**Comment by xavdid** [comment]
@marcinzaremba sorry you're running into this! Can you do a couple of things for me: 

* run `rm -rf node_modules && npm i` to make sure core is up to date

If that doesn't fix it:

* do a `zapier push` so the server has the code that's exhibiting this issue
* comment here with your app id (found in `.zapierapprc`)

We should be able to solve it from there!

**Comment by xavdid** [comment]
Closing for inactivity. If this is still an issue, please feel free to re-open!

**Comment by kangzeroo** [comment]
Hi Zapier! I am also having this issue when attempting to validate or push an App. I have attempted @xavdid suggestions. The error message is the same, but for sake of being verbose here is the log:

$ zapier validate
`Validating project locally.
No structural errors found during validation routine.
This project is structurally sound!

Checking app style.


Error! "https://zapier.com/api/platform/cli/style-check" returned "403" saying "App must validate against schema before checking style"
(Use --debug flag and run this command again to get more details.)`

$ zapier validate --debug
`<< 403
<< {"errors": ["App must validate against schema before checking style"]}


Error: "https://zapier.com/api/platform/cli/style-check" returned "403" saying "App must validate against schema before checking style"
    at /Users/kangzehuang/.nvm/versions/node/v8.10.0/lib/node_modules/zapier-platform-cli/lib/utils/api.js:121:15
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Error!`

My App ID is `9069`. I will keep debugging and post solution here if I find it!

**Comment by xavdid** [comment]
Can you run `zapier -v`? The root of the issue before was a version mismatch between local and the server.

**Comment by kangzeroo** [comment]
Locally:
```
zapier-platform-cli/7.6.1
zapier-platform-core/7.6.1
node/v8.10.0
```
