### ISSUE TITLE
Paths in `zapier test` backtraces are `:censored`

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-cli#75]
When an error occurs during `zapier test` the paths in the backtrace are unusable because fragments of it are replaced with `:censored:....`:

```
Unhandled error: TypeError: Cannot read property 'access_token' of undefined
What happened:
  Starting POST request to :censored:47:3d9c3163dc:/access-token
  Cannot read property 'access_token' of undefined
TypeError: Cannot read property 'access_token' of undefined
    at includeBearerToken (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/:censored:8:b54be9c67e::11:22)
    at Object.<anonymous> (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/zapier-platform-core/src/middleware.js:66:23)
    at bound (domain.js:287:14)
    at Object.runBound (domain.js:300:12)
    at Object.tryCatcher (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/:censored:7:7a4bc07188:/git/:censored:34:c5fb744411:/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
    1) can fetch an access token
```

**Comment by bryanhelmig** [comment]
I don't think we'll be carving out exceptions for exceptions in the censoring values - we've consciously opted for much more aggressive pruning - erring on the side of false positives instead of false negatives.

**Comment by FokkeZB** [comment]
I do think readable paths are quite essential in debugging an Exception and paths shouldn't have any sensitive information (for the developer). I don't know how exactly we're censoring, but couldn't we only sensor the message and not the trace?

**Comment by bryanhelmig** [comment]
Fair point @FokkeZB - we do aggressive pruning on the entire message instead of whitelisting/blacklisting parts of the message. You can take a look at that logic over there https://github.com/zapier/zapier-platform-core/blob/master/src/tools/create-logger.js.

**Comment by FokkeZB** [comment]
@bryanhelmig Would you agree not-censoring stack traces wouldn't hurt since all that stack traces include is the object/function names (which we have access to anyway) and the (local) file paths. I can't think of cases where it'd include keys or such?

What we could do either modify https://github.com/zapier/zapier-platform-core/blob/master/src/tools/create-logger.js#L87 to detect stack traces (`/^    at .+/`) or introduce an escape block that https://github.com/zapier/zapier-platform-core/blob/ada9108c435b5a22cae81c81e4610809c448bb26/src/tools/create-lambda-handler.js#L91 (and other places) could use (e.g. `{% safe %}${err.stack}{% endsafe %}` to wrap data that we don't need to censor. The first one may be better as the second could allow the dev to use this block tag as well.

**Comment by bryanhelmig** [comment]
I think it would be fine in some places, yes -- but maintaining it safely is my chief concern. It seems like tracebacks would be safe to leave uncensored?

**Comment by FokkeZB** [comment]
Fixed via https://github.com/zapier/zapier-platform-core/pull/50
